import dynamic from "next/dynamic";
import type { LogoComponent } from "@/types/logo";
import MonogramLogo from "@/components/service/logos/MonogramLogo";

// Each hand-crafted logo is its own file; loading it via next/dynamic means
// a page importing this map only ships the SVGs for the services it actually
// renders, not the whole catalog's — see AGENTS.md's code-splitting note.
const lazyLogo = (loader: () => Promise<{ default: LogoComponent }>) => dynamic(loader);

export const SERVICE_LOGOS: Record<string, LogoComponent> = {
  github: lazyLogo(() => import("@/components/service/logos/GithubLogo")),
  supabase: lazyLogo(() => import("@/components/service/logos/SupabaseLogo")),
  cloudflare: lazyLogo(() => import("@/components/service/logos/CloudflareLogo")),
  vercel: lazyLogo(() => import("@/components/service/logos/VercelLogo")),
  discord: lazyLogo(() => import("@/components/service/logos/DiscordLogo")),
  npm: lazyLogo(() => import("@/components/service/logos/NpmLogo")),
  digitalocean: lazyLogo(() => import("@/components/service/logos/DigitaloceanLogo")),
  netlify: lazyLogo(() => import("@/components/service/logos/NetlifyLogo")),
  openai: lazyLogo(() => import("@/components/service/logos/OpenaiLogo")),
  zoom: lazyLogo(() => import("@/components/service/logos/ZoomLogo")),
  dropbox: lazyLogo(() => import("@/components/service/logos/DropboxLogo")),
  atlassian: lazyLogo(() => import("@/components/service/logos/AtlassianLogo")),
  twilio: lazyLogo(() => import("@/components/service/logos/TwilioLogo")),
  mongodb: lazyLogo(() => import("@/components/service/logos/MongodbLogo")),
  datadog: lazyLogo(() => import("@/components/service/logos/DatadogLogo")),
  circleci: lazyLogo(() => import("@/components/service/logos/CircleciLogo")),
  sentry: lazyLogo(() => import("@/components/service/logos/SentryLogo")),
  postman: lazyLogo(() => import("@/components/service/logos/PostmanLogo")),
  newrelic: lazyLogo(() => import("@/components/service/logos/NewrelicLogo")),
  bitbucket: lazyLogo(() => import("@/components/service/logos/BitbucketLogo")),
  elastic: lazyLogo(() => import("@/components/service/logos/ElasticLogo")),
  snowflake: lazyLogo(() => import("@/components/service/logos/SnowflakeLogo")),
  cockroachdb: lazyLogo(() => import("@/components/service/logos/CockroachdbLogo")),
  cloudinary: lazyLogo(() => import("@/components/service/logos/CloudinaryLogo")),
  bunny: lazyLogo(() => import("@/components/service/logos/BunnyLogo")),
  wasabi: lazyLogo(() => import("@/components/service/logos/WasabiLogo")),
  mailgun: lazyLogo(() => import("@/components/service/logos/MailgunLogo")),
  brevo: lazyLogo(() => import("@/components/service/logos/BrevoLogo")),
  anthropic: lazyLogo(() => import("@/components/service/logos/AnthropicLogo")),
  elevenlabs: lazyLogo(() => import("@/components/service/logos/ElevenlabsLogo")),
  notion: lazyLogo(() => import("@/components/service/logos/NotionLogo")),
  figma: lazyLogo(() => import("@/components/service/logos/FigmaLogo")),
  airtable: lazyLogo(() => import("@/components/service/logos/AirtableLogo")),
  webflow: lazyLogo(() => import("@/components/service/logos/WebflowLogo")),
  trello: lazyLogo(() => import("@/components/service/logos/TrelloLogo")),
  render: lazyLogo(() => import("@/components/service/logos/RenderLogo")),
  // No hand-crafted brand logo available for these — original two-letter
  // badges instead (see MonogramLogo's own comment for why).
  launchdarkly: ({ size }) => <MonogramLogo size={size} initials="LD" color="#4F46E5" />,
  confluent: ({ size }) => <MonogramLogo size={size} initials="CF" color="#2563EB" />,
  pinecone: ({ size }) => <MonogramLogo size={size} initials="PN" color="#0D9488" />,
  linode: ({ size }) => <MonogramLogo size={size} initials="LN" color="#16A34A" />,
  sendgrid: ({ size }) => <MonogramLogo size={size} initials="SG" color="#0EA5E9" />,
  klaviyo: ({ size }) => <MonogramLogo size={size} initials="KL" color="#F59E0B" />,
  plivo: ({ size }) => <MonogramLogo size={size} initials="PL" color="#E11D48" />,
  cohere: ({ size }) => <MonogramLogo size={size} initials="CH" color="#9333EA" />,
  stabilityai: ({ size }) => <MonogramLogo size={size} initials="SA" color="#334155" />,
  groq: ({ size }) => <MonogramLogo size={size} initials="GR" color="#EA580C" />,
  square: ({ size }) => <MonogramLogo size={size} initials="SQ" color="#1A1A1A" />,
  plaid: ({ size }) => <MonogramLogo size={size} initials="PD" color="#0A6C55" />,
  wise: ({ size }) => <MonogramLogo size={size} initials="WS" color="#037B5D" />,
  chargebee: ({ size }) => <MonogramLogo size={size} initials="CB" color="#E5541B" />,
  klarna: ({ size }) => <MonogramLogo size={size} initials="KA" color="#DB5C93" />,
  clerk: ({ size }) => <MonogramLogo size={size} initials="CK" color="#5B3FD9" />,
  workos: ({ size }) => <MonogramLogo size={size} initials="WO" color="#4F46B8" />,
  duo: ({ size }) => <MonogramLogo size={size} initials="DS" color="#4A8C2A" />,
  pingidentity: ({ size }) => <MonogramLogo size={size} initials="PI" color="#B3261E" />,
  fusionauth: ({ size }) => <MonogramLogo size={size} initials="FA" color="#D9622B" />,
  asana: ({ size }) => <MonogramLogo size={size} initials="AS" color="#D2492A" />,
  monday: ({ size }) => <MonogramLogo size={size} initials="MO" color="#C61A3B" />,
  smartsheet: ({ size }) => <MonogramLogo size={size} initials="SM" color="#005942" />,
};
