import dynamic from "next/dynamic";
import type { LogoComponent } from "@/types/logo";
import MonogramLogo from "@/components/logos/MonogramLogo";

// Each hand-crafted logo is its own file; loading it via next/dynamic means
// a page importing this map only ships the SVGs for the services it actually
// renders, not the whole catalog's — see AGENTS.md's code-splitting note.
const lazyLogo = (loader: () => Promise<{ default: LogoComponent }>) => dynamic(loader);

export const SERVICE_LOGOS: Record<string, LogoComponent> = {
  github: lazyLogo(() => import("@/components/logos/GithubLogo")),
  supabase: lazyLogo(() => import("@/components/logos/SupabaseLogo")),
  cloudflare: lazyLogo(() => import("@/components/logos/CloudflareLogo")),
  vercel: lazyLogo(() => import("@/components/logos/VercelLogo")),
  discord: lazyLogo(() => import("@/components/logos/DiscordLogo")),
  npm: lazyLogo(() => import("@/components/logos/NpmLogo")),
  digitalocean: lazyLogo(() => import("@/components/logos/DigitaloceanLogo")),
  netlify: lazyLogo(() => import("@/components/logos/NetlifyLogo")),
  openai: lazyLogo(() => import("@/components/logos/OpenaiLogo")),
  zoom: lazyLogo(() => import("@/components/logos/ZoomLogo")),
  dropbox: lazyLogo(() => import("@/components/logos/DropboxLogo")),
  atlassian: lazyLogo(() => import("@/components/logos/AtlassianLogo")),
  twilio: lazyLogo(() => import("@/components/logos/TwilioLogo")),
  mongodb: lazyLogo(() => import("@/components/logos/MongodbLogo")),
  datadog: lazyLogo(() => import("@/components/logos/DatadogLogo")),
  circleci: lazyLogo(() => import("@/components/logos/CircleciLogo")),
  sentry: lazyLogo(() => import("@/components/logos/SentryLogo")),
  postman: lazyLogo(() => import("@/components/logos/PostmanLogo")),
  newrelic: lazyLogo(() => import("@/components/logos/NewrelicLogo")),
  bitbucket: lazyLogo(() => import("@/components/logos/BitbucketLogo")),
  elastic: lazyLogo(() => import("@/components/logos/ElasticLogo")),
  snowflake: lazyLogo(() => import("@/components/logos/SnowflakeLogo")),
  cockroachdb: lazyLogo(() => import("@/components/logos/CockroachdbLogo")),
  cloudinary: lazyLogo(() => import("@/components/logos/CloudinaryLogo")),
  bunny: lazyLogo(() => import("@/components/logos/BunnyLogo")),
  wasabi: lazyLogo(() => import("@/components/logos/WasabiLogo")),
  mailgun: lazyLogo(() => import("@/components/logos/MailgunLogo")),
  brevo: lazyLogo(() => import("@/components/logos/BrevoLogo")),
  anthropic: lazyLogo(() => import("@/components/logos/AnthropicLogo")),
  elevenlabs: lazyLogo(() => import("@/components/logos/ElevenlabsLogo")),
  notion: lazyLogo(() => import("@/components/logos/NotionLogo")),
  figma: lazyLogo(() => import("@/components/logos/FigmaLogo")),
  airtable: lazyLogo(() => import("@/components/logos/AirtableLogo")),
  webflow: lazyLogo(() => import("@/components/logos/WebflowLogo")),
  trello: lazyLogo(() => import("@/components/logos/TrelloLogo")),
  render: lazyLogo(() => import("@/components/logos/RenderLogo")),
  calendly: lazyLogo(() => import("@/components/logos/CalendlyLogo")),
  canva: lazyLogo(() => import("@/components/logos/CanvaLogo")),
  "cash-app": lazyLogo(() => import("@/components/logos/CashAppLogo")),
  chef: lazyLogo(() => import("@/components/logos/ChefLogo")),
  "chili-piper": lazyLogo(() => import("@/components/logos/ChiliPiperLogo")),
  "cisco-iot": lazyLogo(() => import("@/components/logos/CiscoIotLogo")),
  "citrix-sharefile": lazyLogo(() => import("@/components/logos/CitrixSharefileLogo")),
  clearbit: lazyLogo(() => import("@/components/logos/ClearbitLogo")),
  clever: lazyLogo(() => import("@/components/logos/CleverLogo")),
  clickfunnels: lazyLogo(() => import("@/components/logos/ClickfunnelsLogo")),
  clicksend: lazyLogo(() => import("@/components/logos/ClicksendLogo")),
  clickup: lazyLogo(() => import("@/components/logos/ClickupLogo")),
  close: lazyLogo(() => import("@/components/logos/CloseLogo")),
  "cloud-66": lazyLogo(() => import("@/components/logos/Cloud66Logo")),
  cloudapp: lazyLogo(() => import("@/components/logos/CloudappLogo")),
  cloudbees: lazyLogo(() => import("@/components/logos/CloudbeesLogo")),
  cloudera: lazyLogo(() => import("@/components/logos/ClouderaLogo")),
  cloudsmith: lazyLogo(() => import("@/components/logos/CloudsmithLogo")),
  cloudways: lazyLogo(() => import("@/components/logos/CloudwaysLogo")),
  clover: lazyLogo(() => import("@/components/logos/CloverLogo")),
  cocoapods: lazyLogo(() => import("@/components/logos/CocoapodsLogo")),
  coda: lazyLogo(() => import("@/components/logos/CodaLogo")),
  codecov: lazyLogo(() => import("@/components/logos/CodecovLogo")),
  codefresh: lazyLogo(() => import("@/components/logos/CodefreshLogo")),
  codewars: lazyLogo(() => import("@/components/logos/CodewarsLogo")),
  coinbase: lazyLogo(() => import("@/components/logos/CoinbaseLogo")),
  "coinbase-commerce": lazyLogo(() => import("@/components/logos/CoinbaseCommerceLogo")),
  "coinbase-prime": lazyLogo(() => import("@/components/logos/CoinbasePrimeLogo")),
  coinmarketcap: lazyLogo(() => import("@/components/logos/CoinmarketcapLogo")),
  copper: lazyLogo(() => import("@/components/logos/CopperLogo")),
  coursera: lazyLogo(() => import("@/components/logos/CourseraLogo")),
  "crates-io": lazyLogo(() => import("@/components/logos/CratesIoLogo")),
  "crypto-com": lazyLogo(() => import("@/components/logos/CryptoComLogo")),
  cypress: lazyLogo(() => import("@/components/logos/CypressLogo")),
  callfire: lazyLogo(() => import("@/components/logos/CallFireLogo")),
  "campfire-hq": lazyLogo(() => import("@/components/logos/CampfireHqLogo")),
  chargify: lazyLogo(() => import("@/components/logos/ChargifyLogo")),
  chatfuel: lazyLogo(() => import("@/components/logos/ChatfuelLogo")),
  checkfront: lazyLogo(() => import("@/components/logos/CheckfrontLogo")),
  "cognito-forms": lazyLogo(() => import("@/components/logos/CognitoFormsLogo")),
  contentful: lazyLogo(() => import("@/components/logos/ContentfulLogo")),
  // No hand-crafted brand logo available for these — original two-letter
  // badges instead (see MonogramLogo's own comment for why).
  launchdarkly: ({ size }) => <MonogramLogo size={size} initials="LD" color="#4F46E5" />,
  confluent: ({ size }) => <MonogramLogo size={size} initials="CF" color="#2563EB" />,
  pinecone: ({ size }) => <MonogramLogo size={size} initials="PN" color="#0D9488" />,
  linode: ({ size }) => <MonogramLogo size={size} initials="LN" color="#16A34A" />,
  sendgrid: ({ size }) => <MonogramLogo size={size} initials="SG" color="#0EA5E9" />,
  klaviyo: ({ size }) => <MonogramLogo size={size} initials="KL" color="#F59E0B" />,
  plivo: ({ size }) => <MonogramLogo size={size} initials="PL" color="#E11D48" />,
  cohere: ({ size }) => <MonogramLogo size={size} initials="CH" color="#9333EA" />,
  stabilityai: ({ size }) => <MonogramLogo size={size} initials="SA" color="#334155" />,
  groq: ({ size }) => <MonogramLogo size={size} initials="GR" color="#EA580C" />,
  square: ({ size }) => <MonogramLogo size={size} initials="SQ" color="#1A1A1A" />,
  plaid: ({ size }) => <MonogramLogo size={size} initials="PD" color="#0A6C55" />,
  wise: ({ size }) => <MonogramLogo size={size} initials="WS" color="#037B5D" />,
  chargebee: ({ size }) => <MonogramLogo size={size} initials="CB" color="#E5541B" />,
  klarna: ({ size }) => <MonogramLogo size={size} initials="KA" color="#DB5C93" />,
  clerk: ({ size }) => <MonogramLogo size={size} initials="CK" color="#5B3FD9" />,
  workos: ({ size }) => <MonogramLogo size={size} initials="WO" color="#4F46B8" />,
  duo: ({ size }) => <MonogramLogo size={size} initials="DS" color="#4A8C2A" />,
  pingidentity: ({ size }) => <MonogramLogo size={size} initials="PI" color="#B3261E" />,
  fusionauth: ({ size }) => <MonogramLogo size={size} initials="FA" color="#D9622B" />,
  asana: ({ size }) => <MonogramLogo size={size} initials="AS" color="#D2492A" />,
  monday: ({ size }) => <MonogramLogo size={size} initials="MO" color="#C61A3B" />,
  smartsheet: ({ size }) => <MonogramLogo size={size} initials="SM" color="#005942" />,
  calix: ({ size }) => <MonogramLogo size={size} initials="CX" color="#0072CE" />,
  callhub: ({ size }) => <MonogramLogo size={size} initials="CH" color="#04B48C" />,
  callrail: ({ size }) => <MonogramLogo size={size} initials="CR" color="#388AED" />,
  cambly: ({ size }) => <MonogramLogo size={size} initials="CM" color="#14A76C" />,
  canary: ({ size }) => <MonogramLogo size={size} initials="CN" color="#FBC02D" />,
  cardconnect: ({ size }) => <MonogramLogo size={size} initials="CC" color="#1B75BC" />,
  "carrot-quest": ({ size }) => <MonogramLogo size={size} initials="CQ" color="#FF7A00" />,
  carta: ({ size }) => <MonogramLogo size={size} initials="CT" color="#5489AD" />,
  "catalyst-cloud": ({ size }) => <MonogramLogo size={size} initials="CC" color="#0EA5A4" />,
  catchpoint: ({ size }) => <MonogramLogo size={size} initials="CP" color="#244A8B" />,
  "catchpoint-systems-node-page": ({ size }) => <MonogramLogo size={size} initials="CP" color="#244A8B" />,
  cdnjs: ({ size }) => <MonogramLogo size={size} initials="CJ" color="#F38020" />,
  celigo: ({ size }) => <MonogramLogo size={size} initials="CG" color="#6C2EB5" />,
  "central-1": ({ size }) => <MonogramLogo size={size} initials="C1" color="#30477B" />,
  centralreach: ({ size }) => <MonogramLogo size={size} initials="CR" color="#002158" />,
  certify: ({ size }) => <MonogramLogo size={size} initials="CY" color="#2E8B57" />,
  "cex-io": ({ size }) => <MonogramLogo size={size} initials="CX" color="#00CCCC" />,
  chameleon: ({ size }) => <MonogramLogo size={size} initials="CH" color="#3DDC97" />,
  channable: ({ size }) => <MonogramLogo size={size} initials="CN" color="#2D6CDF" />,
  "channel-io": ({ size }) => <MonogramLogo size={size} initials="CI" color="#6C4CE3" />,
  chargeover: ({ size }) => <MonogramLogo size={size} initials="CO" color="#2F80ED" />,
  chartbeat: ({ size }) => <MonogramLogo size={size} initials="CB" color="#374151" />,
  chatlio: ({ size }) => <MonogramLogo size={size} initials="CL" color="#2D9CDB" />,
  "check-point": ({ size }) => <MonogramLogo size={size} initials="CP" color="#D61A69" />,
  "chit-chats": ({ size }) => <MonogramLogo size={size} initials="CC" color="#1E88E5" />,
  cigo: ({ size }) => <MonogramLogo size={size} initials="CG" color="#16A085" />,
  circle: ({ size }) => <MonogramLogo size={size} initials="CI" color="#6E56CF" />,
  circleloop: ({ size }) => <MonogramLogo size={size} initials="CL" color="#00A99D" />,
  "cirrus-insight": ({ size }) => <MonogramLogo size={size} initials="CI" color="#3182CE" />,
  "citus-data": ({ size }) => <MonogramLogo size={size} initials="CD" color="#336791" />,
  claravine: ({ size }) => <MonogramLogo size={size} initials="CV" color="#145DA0" />,
  classlink: ({ size }) => <MonogramLogo size={size} initials="CL" color="#0A4D7F" />,
  clearhaus: ({ size }) => <MonogramLogo size={size} initials="CH" color="#00A19A" />,
  "clearwater-analytics": ({ size }) => <MonogramLogo size={size} initials="CA" color="#0B3556" />,
  clevertap: ({ size }) => <MonogramLogo size={size} initials="CT" color="#1076FB" />,
  clicksign: ({ size }) => <MonogramLogo size={size} initials="CS" color="#00C48C" />,
  clio: ({ size }) => <MonogramLogo size={size} initials="CI" color="#0070E0" />,
  clojars: ({ size }) => <MonogramLogo size={size} initials="CJ" color="#63B132" />,
  cloudamqp: ({ size }) => <MonogramLogo size={size} initials="AQ" color="#FF6600" />,
  cloudrepo: ({ size }) => <MonogramLogo size={size} initials="CR" color="#0B7285" />,
  cloudsigma: ({ size }) => <MonogramLogo size={size} initials="CS" color="#0057B8" />,
  cloudsign: ({ size }) => <MonogramLogo size={size} initials="CS" color="#E8552D" />,
  "cm-com": ({ size }) => <MonogramLogo size={size} initials="CM" color="#1657EA" />,
  codat: ({ size }) => <MonogramLogo size={size} initials="CD" color="#0A2540" />,
  "code-climate": ({ size }) => <MonogramLogo size={size} initials="CC" color="#E8593D" />,
  code42: ({ size }) => <MonogramLogo size={size} initials="42" color="#1B3A6B" />,
  codetree: ({ size }) => <MonogramLogo size={size} initials="CT" color="#2E8B57" />,
  codetwo: ({ size }) => <MonogramLogo size={size} initials="C2" color="#1B4A7F" />,
  cohesity: ({ size }) => <MonogramLogo size={size} initials="CO" color="#67BF1B" />,
  coinapi: ({ size }) => <MonogramLogo size={size} initials="CA" color="#1652F0" />,
  coindcx: ({ size }) => <MonogramLogo size={size} initials="DC" color="#0A2540" />,
  coinjar: ({ size }) => <MonogramLogo size={size} initials="CJ" color="#00B37E" />,
  coinlist: ({ size }) => <MonogramLogo size={size} initials="CL" color="#3A4750" />,
  "coins-ph": ({ size }) => <MonogramLogo size={size} initials="CP" color="#F7A600" />,
  comeet: ({ size }) => <MonogramLogo size={size} initials="CM" color="#FF6B5B" />,
  commpeak: ({ size }) => <MonogramLogo size={size} initials="CP" color="#0071CE" />,
  "condo-control": ({ size }) => <MonogramLogo size={size} initials="CC" color="#2E7D32" />,
  contentstack: ({ size }) => <MonogramLogo size={size} initials="CS" color="#E74C3D" />,
  convertkit: ({ size }) => <MonogramLogo size={size} initials="CK" color="#FB6970" />,
  cookpad: ({ size }) => <MonogramLogo size={size} initials="CP" color="#74B72E" />,
  copernica: ({ size }) => <MonogramLogo size={size} initials="CO" color="#6C2EB9" />,
  coralogix: ({ size }) => <MonogramLogo size={size} initials="CX" color="#7C3AED" />,
  corlytics: ({ size }) => <MonogramLogo size={size} initials="CL" color="#4B0082" />,
  cornerstone: ({ size }) => <MonogramLogo size={size} initials="CN" color="#0057FF" />,
  coschedule: ({ size }) => <MonogramLogo size={size} initials="CS" color="#17A2B8" />,
  courier: ({ size }) => <MonogramLogo size={size} initials="CR" color="#00C2A8" />,
  "coveo-cloud-v2": ({ size }) => <MonogramLogo size={size} initials="CV" color="#323155" />,
  coveralls: ({ size }) => <MonogramLogo size={size} initials="CV" color="#E91E63" />,
  cradlepoint: ({ size }) => <MonogramLogo size={size} initials="CP" color="#003057" />,
  cronofy: ({ size }) => <MonogramLogo size={size} initials="CR" color="#D6002A" />,
  crowdcast: ({ size }) => <MonogramLogo size={size} initials="CC" color="#7B2FF7" />,
  "crucial-hosting": ({ size }) => <MonogramLogo size={size} initials="CH" color="#00A8A8" />,
  currencycloud: ({ size }) => <MonogramLogo size={size} initials="CC" color="#F5822B" />,
  curve: ({ size }) => <MonogramLogo size={size} initials="CV" color="#1B1B1F" />,
  "customer-io": ({ size }) => <MonogramLogo size={size} initials="CI" color="#0B353B" />,
  cybersmart: ({ size }) => <MonogramLogo size={size} initials="CS" color="#1E3A8A" />,
  cycode: ({ size }) => <MonogramLogo size={size} initials="CY" color="#5B21B6" />,
  cytracom: ({ size }) => <MonogramLogo size={size} initials="CY" color="#0F4C81" />,
};
