#!/usr/bin/env node
// Generates docs/COMPONENTS.md — a props reference for every React
// component under components/, extracted straight from their TypeScript
// types via react-docgen-typescript (drives the real TS compiler, so it
// resolves the @/* alias and cross-file imported prop types correctly).
//
// Run with: npm run docs:components

import { readdirSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { withCustomConfig } from "react-docgen-typescript";

const ROOT = process.cwd();
const COMPONENTS_DIR = path.join(ROOT, "components");
const OUT_FILE = path.join(ROOT, "docs", "COMPONENTS.md");

function listTsxFiles(dir) {
  return readdirSync(dir, { recursive: true })
    .filter((entry) => entry.endsWith(".tsx"))
    .map((entry) => path.join(dir, entry));
}

function escapeCell(value) {
  return String(value).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function formatDefault(defaultValue) {
  if (defaultValue === undefined || defaultValue === null) return "—";
  if (typeof defaultValue === "object" && "value" in defaultValue) {
    return escapeCell(defaultValue.value);
  }
  return escapeCell(defaultValue);
}

function renderComponent(doc) {
  const relPath = path.relative(ROOT, doc.filePath).replace(/\\/g, "/");
  const lines = [`### ${doc.displayName}`, "", `\`${relPath}\``, ""];

  if (doc.description) lines.push(doc.description, "");

  const props = Object.values(doc.props);
  if (props.length === 0) {
    lines.push("_No props._", "");
    return lines.join("\n");
  }

  lines.push("| Prop | Type | Required | Default | Description |");
  lines.push("|---|---|---|---|---|");
  for (const prop of props) {
    lines.push(
      `| ${escapeCell(prop.name)} | ${escapeCell(prop.type.name)} | ${prop.required ? "Yes" : "No"} | ${formatDefault(prop.defaultValue)} | ${escapeCell(prop.description || "")} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function main() {
  const files = listTsxFiles(COMPONENTS_DIR);
  const parser = withCustomConfig(path.join(ROOT, "tsconfig.json"), {});

  const docs = [];
  for (const file of files) {
    try {
      docs.push(...parser.parse(file));
    } catch (err) {
      console.warn(`  skip ${path.relative(ROOT, file)}: ${err.message}`);
    }
  }

  docs.sort((a, b) => a.filePath.localeCompare(b.filePath) || a.displayName.localeCompare(b.displayName));

  const header = [
    "# Component props reference",
    "",
    `Generated by \`npm run docs:components\` (react-docgen-typescript) — do not edit by hand, re-run the script instead.`,
    "",
  ];

  const body = docs.map(renderComponent);
  mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, [...header, ...body].join("\n"));

  console.log(`Documented ${docs.length} component(s) across ${files.length} file(s) -> docs/COMPONENTS.md`);
}

main();
